app/routes.php
<?php

//Route::controller('commentsapi', 'CommentsController');
// event Resource
Route::resource('comments', 'CommentsController');

// event Resource
Route::resource('events', 'EventsController');

//bc fuck resource box
Route::controller('eventsapi', 'EventsController');

//bc fuck resource box
Route::controller('locatiiapi', 'LocatiiController');

//bc fuck resource PDF_show_boxed(p, text, left, top, width, height, mode, feature)
Route::controller('convocariapi', 'ConvocariController');

//bc fuck resource box
Route::controller('convocari', 'ConvocariController');

//bc fuck resource box
//Route::controller('sports', 'SportsController');
Route::get('profile/notificari', 'NotificariController@index');
Route::post('profile/notificari', 'NotificariController@update');
Route::get('dezabonare', 'NotificariController@dezabonare');


Route::get('profile/pwd', 'ProfileController@getPwd');
Route::post('profile/pwd', 'ProfileController@postPwd');

Route::resource('profile', 'ProfileController', array("only" => array('index', "show", "edit", "update")));



View::composer('_parts.menu', function($view){
   $sports = Sport::active()->with(array('subcategorii' => function($query) {
      $query->active();
   }))->active()->get()->toArray();


   /* replaced with eager loading
   foreach($sports as &$sport) {
      $sport['subcategorii'] = Sport::find($sport['id'])->subcategorii()->active()->get()->toArray();
   }
   */
   //$view
   //View::share('leftmenuSports', $sports);
   $view->with('sports', $sports);
});





Route::get('forgot', function() {
   return View::make('auth.forgot');
});

Route::post('forgot', function() {

   $rules = array('email' => 'required|email');
   $v = Validator::make(Input::all(), $rules);

   if ($v->fails()) {
      return Redirect::back()->withInput()->withErrors($v);
   }

   $user = User::where('email', '=', Input::get('email'))->first();


   $pwd = Str::random(10);
   $user->password = Hash::make($pwd);

   $data = array('password' => $pwd);
   Mail::send('emails/auth/forgot', $data, function($message) use ($user)
   {
      $message->to($user->email)
      ->subject('vreausajoc - o nou user s-a inregistrat');
   });

   $user->save();

   Session::flash('message', 'Parola schimbata cu succes. <br />Noua parola ai primit-o pe email.');
   return Redirect::to('login');
});


Route::get('register', function() {
   $captcha = new Services\Validators\privateReCaptcha;

   $gen = Config::get('sitesettings.userGen');

   $pageTitle = 'Inregistreare utilizator';
   $pageDescription = 'Inregistrare utilizator vreausajoc.ro. Intra in comunitarea vreau sa joc, sa faci sport';
   return View::make('auth.register')
   ->with('sports',Sport::active()->lists('name', 'id'))
   ->with('captcha', $captcha)
   ->with(compact('gen'))
   ->with(compact('pageDescription'))
   ->with(compact('pageTitle'));
});

Route::post('register', function() {
   $v = User::validate(Input::all());

   if ($v->passes()) {

      $rules = array('email' => 'unique:users');
      $v = User::validate(Input::all(), $rules);
      if ($v->passes()) {
         $user = new User;
         $user->firstname = Input::get('first_name');
         $user->lastname  = Input::get('last_name');
         $user->email      = Input::get('email');
         $user->gen      = Input::get('gen');
         $user->password   = Hash::make(Input::get('password'));
         $user->alias   = $user->firstname . ' ' . $user->lastname;
         //$user->sport_id      = Input::has('sport') ? intval(Input::get('sport')) : null;
         if ($user->save()) {
            $user->sports()->attach(intval(Input::get('sport')));

            Log::info('['.__METHOD__.'] User id ['.$user->id.'] created.');


            /*
            |
            | Sending emails.
            |
             */
            $userId = $user->id;
            Queue::push(function($job) use ($userId) {
               $user = User::find($userId);
               $data = [ 'user' => $user ];

               /*
               |
               | Sending emails.
               |
               */
               Mail::send('emails/welcome', $data, function($message) use ($user) {
                  $message->to($user->email)
                        ->subject('Contul tau la vreausajoc.ro');
               });


               Mail::send('emails/auth/newuser', $data, function($message)
               {
                  $message->to(Config::get('sitesettings.enotif.users', 'bogdan.durla@gmail.com'))
                     ->subject('vreausajoc - o nou user s-a inregistrat');
               });


               $job->delete();
            });



            Auth::login($user);

            Log::info('['.__METHOD__.'] redirecting ['.$user->id.'] to profile.');

            return Redirect::to('profile/');
         }
      }
      /*
      $user = new stdClass;
      $user->name = 'Bogdan';
      $user->email = 'bogdan.durla@gmail.com';
      $data = [ 'user' => $user ];

      var_dump($user);
      */

      // email view, data for view, closure to send email
      /*
      Mail::send('emails/auth/welcome', $data, function($message) use ($user)
      {
         $message->to($user->email)->subject('Bine ai venit la vreausajoc!');
      });
      */

      //return 'Welcome email sent!';
}


return Redirect::to('register')
->with('flash_error', 'Crearea de user a esuat')
->withInput(Input::except('password'))
->withErrors($v->messages());



});


Route::get('/logout', array('as' => 'logout', function () {
  Auth::logout();

  return Redirect::to('/')
  ->with('flash_notice', 'You are successfully logged out.');
}))->before('auth');



Route::get('/login', function() {
   $pageTitle = 'Login utilizator';
   $pageDescription = 'Login utilizator vreausajoc.ro. Intra in comunitarea vreau sa joc, sa faci sport';
   return View::make('auth.login')
   ->with('message', false)
   ->with('email', false)
   ->with(compact('pageTitle'))
   ->with(compact('pageDescription'));

})->before('guest');;

Route::post('/login', function() {
   $credentials = array(
     'email' => Input::get('email'),
     'password' => Input::get('password')
     );

   //var_dump($credentials);

   $password = Hash::make(Input::get('password'));
   // perform validation
   if ( Auth::attempt($credentials) )
   {
      // Credentials match. Logged in!
      //echo 'valid';
      Auth::user()->touch();
      //Symfony\Component\HttpFoundation\Request::trustProxyData();
      Log::info('['.__METHOD__.'] User id ['.Auth::user()->id.'] IP ['.Request::getClientIp().'] logged in');
      //User::find(Auth::user()->id)->touch();

      return Redirect::intended('profile/');
   }
   Log::error('['.Input::get('email') .' failed to login.]');

   return Redirect::to('login')
   ->with('flash_error', 'Combinatia email/parola a fost incorecta.')
   ->withInput(Input::except('password'));
});






/*
|--------------------------------------------------------------------------
| Root /
|--------------------------------------------------------------------------
|
| Here you may configure the connection information for each server that
| is used by your application. A default configuration has been added
| for each back-end shipped with Laravel. You are free to add more.
|
*/
Route::get('/', function() {

   $last10events  = UserEvent::last()->with('orase')->orderBy('created_at')->take(Config::get('sitesettings.lastXevents', 10))->get();
   $last10users   = User::last()->orderBy('created_at')->take(Config::get('sitesettings.lastXusers', 10))->get();
   $last10locatii = Locatie::last()->with('orase')->orderBy('created_at')->take(Config::get('sitesettings.lastXlocatii', 10))->get();;

   $out = merge($last10events, $last10users, function($a1, $a2) {
      return -(strcmp($a1->created_at, $a2->created_at));
   });

   $out = merge($out, $last10locatii, function($a1, $a2) {
      return -(strcmp($a1->created_at, $a2->created_at));
   });

   $ultimeleXnoutati = $out->slice(0, Config::get('sitesettings.ultimeleXnoutati', 10));

   return View::make('index')
      ->with(compact('ultimeleXnoutati'));
});








//add a location
//used in create/edit event
Route::post('locatii/add/', function() {

   $rules = array(
      'name' => 'Required|Min:3|Max:250|noxss_tags',
      'address' => 'Required|Min:5|Max:500|noxss_tags',
      'localitate' => 'Required|Min:1|noxss_tags',
      'sport' => 'Required|Min:1|noxss_tags',
      );

   $v = Validator::make(Input::all(), $rules);
   if ($v->fails()) {
      Log::warning('['.__METHOD__.'] failed to validate arena' . print_r(Input::all(),1));
      $messages = '';
      foreach ($v->messages()->all() as $value) {
         $messages .= $value . ' ';
      }
      return Response::json(array('status' => 'error', 'msg' => 'Adaugarea de arena a esuat.' . $messages));
   }

   $locatie = new Locatie;
   $locatie->name = Input::get('name');
   $locatie->adresa = Input::get('address');
   $locatie->oras_id = Input::get('localitate');
   $locatie->added_by_user_id = Auth::user()->id;

   $locatie->save();

   $locatie->sports()->sync(array('sport_id' => Input::get('sport')));

   $emailArr = $locatie->toArray();
   $emailArr['adresa'] = $locatie->adresa;
   $emailArr['oras'] = $locatie->orase->oras;
   $emailArr['sport'] = $locatie->sports()->first()->name;
   $emailArr['added_by_user_id'] = $locatie->added_by_user_id;
   $emailArr['alias'] = Auth::user()->alias;

   $data = array('emailArr' => $emailArr);

   Mail::send('emails/locatii/newlocatie', $data, function($message) use($emailArr)
   {
      $message->to(Config::get('sitesettings.enotif.areneadmin', 'bogdan.durla@gmail.com'))
      ->subject('vreausajoc - o noua admin locatie a fost adaugata');
   });



   //@todo send email to admin
   return Response::json(array('id' => $locatie->id, 'status' => 'ok', 'msg' => 'Arena a fost adaugata.'));

})->before('auth');




//vsj.ro/locatii/sport-locatii/3
//@called in create/edit event

app/views/events/create.blade.php
@extends('master')

@section('head')
   @parent
   {{ Html::style('css/jquery-ui-1.10.0.custom.min.css') }}
   {{ Html::script('js/jquery-ui-1.10.0.custom.min.js') }}
   {{ Html::script('js/jquery-ui-timepicker-addon.js') }}


   {{ Html::style('css/chosen/chosen.css') }}
   {{ Html::script('js/chosen/chosen.jquery.js') }}

    <script type="text/javascript">
       $(function() {
          $.datepicker.setDefaults({
             dateFormat: 'DD, d MM yy',
             dayNames: ['Duminica', 'Luni', 'Marti', 'Miercuri', 'Joi', 'Vineri', 'Sambata'],
             monthNames: ['Ianuarie','Februarie','Martie','Aprilie','Mai','Iunie','Iulie','August','Septembrie','Octombrie','Noiembrie','Decemberie']
          });
       });
    </script>

@stop

@section('breadcrumb')
   <li class="active">
      <a href="{{route('events.index')}}">Evenimente</a>
      <span class="divider">/</span>
   </li>

   <li class="active">
      @if ($event->id) Editeaza eveniment @else Creeaza eveniment @endif
   </li>
@stop

@section('content')


@if ($event->id)
{{ Form::open(array(
   'method' => 'put',
   'route' => array('events.update', $event->id),
   'class' => "form-horizontal well")) }}
@else
{{ Form::open(array(
   'route' => array('events.store'),
   'class' => "form-horizontal well")) }}
@endif

<div>
<p class="bold">Numele evenimentului</p>
{{Form::text('event', Input::old('event') ? Input::old('event') : $event->event)}}
</div>

<div>
<p class="bold">Sportul</p>
{{Form::select('sport_id', $sports, Input::old('sport_id') ? Input::old('sport_id') : $event->sport_id);}}

</div>

<?php
$arenaIsbhidden = (isset($event) && $event->arena_id ? $event->arena_id : (Input::old('arena_id') ? Input::old('arena_id') : false)) ? '' : 'bhidden';
?>

<div class="arenaholder <?php echo $arenaIsbhidden?>">
<p class="bold">Arena / Teren </p>
   <div style="float:left">

   {{Form::select('arena_id', $arene, Input::old('arena_id') ? Input::old('arena_id') : $event->arena_id, array('class' => "arena","data-placeholder" => "Alege o arena..."));}}
   </div>

   <div class="<?php echo (count($arene) ?  'bhidden' : '')?> holderadaugapopup" style="float:left">
      &nbsp;Locatia nu e in lista? <a class="adaugapopup" href="javascript:void(0);">Adauga locatia</a>
   </div>
   <div style="clear: both;float: none;"></div>
</div>

<div>
   <p class="bold">Data si ora</p>
   {{Form::text('data', Input::old('data') ? Input::old('data') : date2js($event->data),
      array("id" =>"datepicker"))}}
ora
   {{Form::text('ora', Input::old('ora') ? Input::old('ora') : time2js($event->ora),
      array("id" =>"timepicker"))}}
</div>

<div>
<p class="bold">Locatie</p>
{{Form::select('oras_id', $orase, Input::old('oras_id') ? Input::old('oras_id') : $event->oras_id, array("class"=>"localitate"))}}
</div>

<?php

/*delayed for future versions
<div>
<p class="bold">Eveniment de tip</p>
<?php
$eventTypes = array(
   array('id' => TYPE_PUBLIC, 'name' => TYPE_PUBLIC_TEXT),
   array('id' => TYPE_PRIVATE, 'name' => TYPE_PRIVATE_TEXT)
);
echo form_simple_dropdown('tip_eveniment', $eventTypes, 'id', 'name',
   array(), isset($event) ? $event->arena_id : set_value('tip_eveniment'));
?>
</div>
*/
?>

<div>
<p class="bold">Pret de persoana</p>

{{Form::text('pret', Input::old('pret') ? Input::old('pret') : $event->pret)}}
Lei
</div>

<div>
<p class="bold">Nr. locuri disponibile</p>
{{Form::text('locuri', Input::old('locuri') ? Input::old('locuri') : $event->locuri)}}
</div>

<?php
/*if ($this->ion_auth->logged_id() == EVENT_OWNER_ID) {*/
?>

<div>
<br />
{{Form::submit($event->id ? 'Salveaza modificarile' : 'Creeaza eveniment', array('class' => "btn btn-primary"))}}
&nbsp;
{{Form::reset('Reset', array('class' => 'btn'))}}
{{Form::close()}}
</div>

<script type="text/javascript">
$(function() {
  var firstRedir = true;
   $.datepicker.setDefaults({
      dateFormat: 'DD, d MM yy',
      dayNames: ['Duminica', 'Luni', 'Marti', 'Miercuri', 'Joi', 'Vineri', 'Sambata'],
      monthNames: ['Ianuarie','Februarie','Martie','Aprilie','Mai','Iunie','Iulie','August','Septembrie','Octombrie','Noiembrie','Decemberie']
    });


   /*
   $('#datepicker').datetimepicker({
      dateFormat: 'DD, d MM yy',
      hourGrid: 4,
      minuteGrid: 10,
      timeFormat: 'hh:mm'
   });
   */

   $( "#datepicker").datepicker({
      showOtherMonths: true,
      selectOtherMonths: true,
      showButtonPanel: true,
      minDate: 0,
      showOn: "both",
      buttonImage: '{{ URL::asset('/img/icalsm.png') }}',
      buttonImageOnly: true
   });

   $('#timepicker').timepicker({
      hourGrid: 4,
      minuteGrid: 10,
      timeFormat: 'HH:mm',
      showOn: "both",
      buttonImage: '{{ URL::asset('/img/clock.png') }}',
      buttonImageOnly: true
   });

   $('.arena').chosen({no_results_text: "Nici o locatie nu contine"}).change(function() {
      //$('.holderadaugapopup').show();
   });

   $(document).on('keyup', '.chzn-search input', function() {
      if ($('.chzn-drop .no-results').is(':visible')) {
         var value = $('.chzn-search input').val();
         $( "#locatiedialog-form" ).data('search', {
            "searched": value,
            "sportId": $('select[name="sport_id"]').val(),
            "sportName": $('select[name="sport_id"] option:selected').text()
         });
      }
   });

   $('.adaugapopup').click(function() {
      $( "#locatiedialog-form" ).dialog( "open" );
   });

   $('select[name="sport_id"]').change(function() {
      $('.holderadaugapopup').show();
      //ajax get arenes filtrare dupa sport.$
      var that = $(this);
      var sportId = $(this).val();
      var locatieId = $('.localitate').val();
      if (isNaN(parseInt(sportId,10))) {
         return false;
      }
      $.get('{{URL::to("/locatii/sport-locatii/")}}' + '/' + sportId,
         function(data) {
            $('.arena').empty();
            $('.arena').append($('<option>').text('Alege o arena').attr('value', '0'));
            $.each(data.locatii, function(key,value) {
               $('.arena').append($('<option>').text(value.name).attr('value', value.id));
            });
            @if (Input::has('aid')) {
              if (firstRedir) {
                $('.arena').val({{(int)Input::get('aid')}});
              }
              firstRedir = false;
            }
            @elseif (Input::old('arena_id'))
               $('.arena').val({{(int)Input::old('arena_id')}});
            @endif
            if (that.data("selected") && that.data("selected")) {
               $('.arena').val(that.data("selected"));
            }
            $(".arena").trigger("liszt:updated");

         }
      , "json");

      $('.arenaholder').show();
   });
   //$('arenaholder').show();

   //$('.holderadaugapopup').show();
   //$( "#locatiedialog-form" ).dialog( "open" );
   //@todo remove it
   // $('.go').trigger('click');
});
</script>

<div class="locatiedialog-form" id="locatiedialog-form"
   title="Adauga arena">
<p class="validateTips">Toate campurile sunt obligatorii</p>
<form>
<fieldset><label for="name">Numele locatiei</label> <input type="text"
   name="name" id="name" class="text ui-widget-content ui-corner-all" />
   <label for="email">Adresa locatiei</label> <input type="text"
   name="address" id="address" value=""
   class="text ui-widget-content ui-corner-all" /> <label for="email">Orasul</label>
   {{Form::select('dialoglocalitate', $orase, Input::old('oras_id') ? Input::old('oras_id') : $event->oras_id, array("class"=>"dialoglocalitate"))}}
</fieldset>
</form>
</div>

<script type="text/javascript">
$(function() {

  @if (Input::has('sid') || Input::old('sport_id'))
    $('select[name="sport_id"]').trigger('change');
  @endif


   var name = $( "#name" ),
     address = $( "#address" ),
     localitate = $( ".dialoglocalitate:visible" ),
     allFields = $( [] ).add( name ).add( address ).add( localitate ),
     tips = $( ".validateTips" );

   function updateTips( t ) {
     tips
       .text( t )
       .addClass( "ui-state-highlight" );
     setTimeout(function() {
       tips.removeClass( "ui-state-highlight", 1500 );
     }, 500 );
   }

   function checkLength( o, n, min, max ) {
     if ( o.val().length > max || o.val().length < min ) {
       o.addClass( "ui-state-error" );
       updateTips( "Numarul de caractere pentru " + n + " trebuie sa fie intre " +
         min + " si " + max + "." );
       return false;
     } else {
       return true;
     }
   }

   function checkRegexp( o, regexp, n ) {
     if ( !( regexp.test( o.val() ) ) ) {
       o.addClass( "ui-state-error" );
       updateTips( n );
       return false;
     } else {
       return true;
     }
   }

   $( "#locatiedialog-form" ).dialog({
     autoOpen: false,
     height: 'auto',
     width: 555,
     modal: true,
     open: function() {
        if ($(this).data("search")) {
           name.val($(this).data("search").searched);
           $( "#locatiedialog-form" ).dialog( "option", "title", "Adauga arena " + $(this).data("search").sportName);
        }

     },
     buttons: {
       "Adauga": function() {
         var bValid = true;
         allFields.removeClass( "ui-state-error" );

         bValid = bValid && checkLength( name, "numele locatiei", 3, 250 );
         bValid = bValid && checkLength( address, "adresa locatiei", 5, 500 );
         bValid = bValid && checkRegexp( localitate, /^[1-9][0-9]*/,"Orasul lipseste. Alege un oras din lista." );
         bValid = bValid && checkRegexp( localitate, /^(?!45$)/,"Orasul lipseste. Alege un oras din lista." );

         var sport_val = parseInt($('select[name="sport_id"]').val(), 10);
         if (isNaN(sport_val) || !sport_val) {
            updateTips('Nu ai selectat nici un sport pentru aceasta arena.');
            bValid = false;
         }

         if ( bValid ) {
            var $that = $(this);
            $.post(
               "/locatii/add/",
               { "name": name.val(), "address": address.val(), "localitate": localitate.val(), "sport":sport_val },
               function(data){
                  if (data.status == 'ok') {
                     $('select[name="sport_id"]').data("selected", data.id);
                     $('select[name="sport_id"]').trigger('change');
                     $that.dialog( "close" );
                  }
                  else {
                     updateTips(data.msg);
                  }
               }, "json");
         }
       },
       "Renunta": function() {
         $( this ).dialog( "close" );
       }
     },
     close: function() {
       allFields.val( "" ).removeClass( "ui-state-error" );
       $(this).data('search', "");
     }
   });
 });
</script>


@stop {{-- content --}}

app/views/events/index.blade.php
@extends('master')

@section('content')

@section('breadcrumb')
   <li class="active">Evenimente</li>
@stop

<div>
   <a href="{{route('events.create')}}" class="btn btn-primary">Creeaza eveniment</a>
   <br />
   <br />
</div>

@if ($events)
<table class="table table-hover table-striped">
<tr>
   <th>Eveniment</th>
   <th>Data</th>
   <th>Ora</th>
   <th>Sport</th>
   <th>Arena</th>
   <th>Actiuni</th>
</tr>

@foreach($events as $row)

   <?php $expired = strtotime($row->data . ' ' . $row->ora) < strtotime("now"); ?>

   <tr class="@if($expired) faded @endif">
      <td>
         <a href="{{route('events.show' , $row->id)}}">{{$row->event}}</a>
      </td>
      <td>@if ($expired)<strike>@endif
          {{date2js($row->data)}}
          @if ($expired)</strike>@endif
       </td>
      <td>{{time2js($row->ora)}} </td>

      <td>{{-- $row->sports->name --}} </td>
      <td>
         {{a_locatie($row->arene)}}
      </td>
      <td>
         <a href="{{route('events.edit', $row->id)}}">Edit</a> |
         @if ($row->active)
            <a href="{{URL::action('EventsController@getHide', $row->id)}}">Ascunde</a>
         @else
            <a href="{{URL::action('EventsController@getShow', $row->id)}}">Activeaza</a>
         @endif
      </td>
   </tr>
@endforeach

</table>

{{$events->links()}}

@endif

@stop

app/views/events/show.blade.php
@extends('master')

@section('head')
   @parent
   {{ Html::style('css/jquery-ui-1.10.0.custom.min.css') }}
   {{ Html::script('js/jquery-ui-1.10.0.custom.min.js') }}
@stop

@section('content')


@section('breadcrumb')
   <li class="active">
      <a href="{{route('events.index')}}">Evenimente</a>
      <span class="divider">/</span>
   </li>

   <li class="active">
      {{$event->event}}
   </li>
@stop


<div class="panel panel-default">
   <div class="panel-heading comment-counter">
      <h4>{{$event->event}}
         <small>eveniment {{$event->sports->name}}, organizat de {{a_profile($event->users)}}
      </h4>
   </div>

   <div class="panel-body">

   <address>
      <strong>
         <div class="pull-right">
            <div class="panel panel-default">
              <div class="panel-heading">
                  <div class="tc">Data eveniment</div>
               </div>
               <div class="panel-body">
                  <div id="datepicker"></div>
               </div>
            </div>
         </div>
         <a href="{{URL::to('sports/' . $event->sports->name)}}">{{$event->sports->name}}</a>:
         {{date2js($event->data);}}
       ora
         {{time2js($event->ora);}}

      </strong>
   <br />


   Locatia:
      {{a_locatie($event->arene)}},
      <span>{{ucfirst(strtolower($event->orase->oras))}}</span>
      {{-- {{$event->arene->orase->name}} --}}
   <br />
   </address>

   <address>
     Organizator:
      {{a_profile($event->users)}}
   </address>

   Pret de persoana:
   <?php
   echo $event->pret;
   ?> Lei
   <br />
   Locuri disponibile:
   <?php
   echo $event->locuri;
   ?>

   <?php
      $notIn = 0;
   ?>
   @if (count($participanti))
   <br /> Lista participanti<br />
   <ul>
   @foreach($participanti as $participant)
   <?php
   $notIn = 0;
   if (is_logged() == $participant->destids->id) {
      $notIn = 1;
   }
   ?>
     <li>{{a_profile($participant->destids)}}</li>
   @endforeach
   </ul>
   @endif

   <br /><br />
   @if ((!is_logged() || $event->user_id != Auth::user()->id) && $event->locuri && !$notIn)
      <div class="holder">
         Esti intersat de acest eveniment?
            <a id="event_{{$event->id}}" class="btn btn-success btn-small vreausajoc" href="javascript:;">
               Vreau sa joc!
            </a>
      </div>

      <br /><br />
      @include('_parts.vreausajoc')
   @endif

<div class="clearfix"></div>
<br />

@include('_parts.comments')
   </div>
</div>

@stop

@section('footer')
   @parent
   <script>
   $(function() {
      $( "#datepicker" ).datepicker({
         dateFormat: "yy-mm-dd"
      });
      $( "#datepicker" ).datepicker("setDate", "{{$event->data}}");
      $( "#datepicker a" ).removeClass('ui-state-highlight');
      $( "#datepicker a.ui-state-active" ).addClass('ui-state-highlight');
   });
   </script>
@stop