app/routes.php
<?php

//Route::controller('commentsapi', 'CommentsController');
// event Resource
Route::resource('comments', 'CommentsController');

// event Resource
Route::resource('events', 'EventsController');

//bc fuck resource box
Route::controller('eventsapi', 'EventsController');

//bc fuck resource box
Route::controller('locatiiapi', 'LocatiiController');

//bc fuck resource PDF_show_boxed(p, text, left, top, width, height, mode, feature)
Route::controller('convocariapi', 'ConvocariController');

//bc fuck resource box
Route::controller('convocari', 'ConvocariController');

//bc fuck resource box
//Route::controller('sports', 'SportsController');
Route::get('profile/notificari', 'NotificariController@index');
Route::post('profile/notificari', 'NotificariController@update');
Route::get('dezabonare', 'NotificariController@dezabonare');


Route::get('profile/pwd', 'ProfileController@getPwd');
Route::post('profile/pwd', 'ProfileController@postPwd');

Route::resource('profile', 'ProfileController', array("only" => array('index', "show", "edit", "update")));



View::composer('_parts.menu', function($view){
   $sports = Sport::active()->with(array('subcategorii' => function($query) {
      $query->active();
   }))->active()->get()->toArray();


   /* replaced with eager loading
   foreach($sports as &$sport) {
      $sport['subcategorii'] = Sport::find($sport['id'])->subcategorii()->active()->get()->toArray();
   }
   */
   //$view
   //View::share('leftmenuSports', $sports);
   $view->with('sports', $sports);
});





Route::get('forgot', function() {
   return View::make('auth.forgot');
});

Route::post('forgot', function() {

   $rules = array('email' => 'required|email');
   $v = Validator::make(Input::all(), $rules);

   if ($v->fails()) {
      return Redirect::back()->withInput()->withErrors($v);
   }

   $user = User::where('email', '=', Input::get('email'))->first();


   $pwd = Str::random(10);
   $user->password = Hash::make($pwd);

   $data = array('password' => $pwd);
   Mail::send('emails/auth/forgot', $data, function($message) use ($user)
   {
      $message->to($user->email)
      ->subject('vreausajoc - o nou user s-a inregistrat');
   });

   $user->save();

   Session::flash('message', 'Parola schimbata cu succes. <br />Noua parola ai primit-o pe email.');
   return Redirect::to('login');
});


Route::get('register', function() {
   $captcha = new Services\Validators\privateReCaptcha;

   $gen = Config::get('sitesettings.userGen');

   $pageTitle = 'Inregistreare utilizator';
   $pageDescription = 'Inregistrare utilizator vreausajoc.ro. Intra in comunitarea vreau sa joc, sa faci sport';
   return View::make('auth.register')
   ->with('sports',Sport::active()->lists('name', 'id'))
   ->with('captcha', $captcha)
   ->with(compact('gen'))
   ->with(compact('pageDescription'))
   ->with(compact('pageTitle'));
});

Route::post('register', function() {
   $v = User::validate(Input::all());

   if ($v->passes()) {

      $rules = array('email' => 'unique:users');
      $v = User::validate(Input::all(), $rules);
      if ($v->passes()) {
         $user = new User;
         $user->firstname = Input::get('first_name');
         $user->lastname  = Input::get('last_name');
         $user->email      = Input::get('email');
         $user->gen      = Input::get('gen');
         $user->password   = Hash::make(Input::get('password'));
         $user->alias   = $user->firstname . ' ' . $user->lastname;
         //$user->sport_id      = Input::has('sport') ? intval(Input::get('sport')) : null;
         if ($user->save()) {
            $user->sports()->attach(intval(Input::get('sport')));

            Log::info('['.__METHOD__.'] User id ['.$user->id.'] created.');


            /*
            |
            | Sending emails.
            |
             */
            $userId = $user->id;
            Queue::push(function($job) use ($userId) {
               $user = User::find($userId);
               $data = [ 'user' => $user ];

               /*
               |
               | Sending emails.
               |
               */
               Mail::send('emails/welcome', $data, function($message) use ($user) {
                  $message->to($user->email)
                        ->subject('Contul tau la vreausajoc.ro');
               });


               Mail::send('emails/auth/newuser', $data, function($message)
               {
                  $message->to(Config::get('sitesettings.enotif.users', 'bogdan.durla@gmail.com'))
                     ->subject('vreausajoc - o nou user s-a inregistrat');
               });


               $job->delete();
            });



            Auth::login($user);

            Log::info('['.__METHOD__.'] redirecting ['.$user->id.'] to profile.');

            return Redirect::to('profile/');
         }
      }
      /*
      $user = new stdClass;
      $user->name = 'Bogdan';
      $user->email = 'bogdan.durla@gmail.com';
      $data = [ 'user' => $user ];

      var_dump($user);
      */

      // email view, data for view, closure to send email
      /*
      Mail::send('emails/auth/welcome', $data, function($message) use ($user)
      {
         $message->to($user->email)->subject('Bine ai venit la vreausajoc!');
      });
      */

      //return 'Welcome email sent!';
}


return Redirect::to('register')
->with('flash_error', 'Crearea de user a esuat')
->withInput(Input::except('password'))
->withErrors($v->messages());



});


Route::get('/logout', array('as' => 'logout', function () {
  Auth::logout();

  return Redirect::to('/')
  ->with('flash_notice', 'You are successfully logged out.');
}))->before('auth');



Route::get('/login', function() {
   $pageTitle = 'Login utilizator';
   $pageDescription = 'Login utilizator vreausajoc.ro. Intra in comunitarea vreau sa joc, sa faci sport';
   return View::make('auth.login')
   ->with('message', false)
   ->with('email', false)
   ->with(compact('pageTitle'))
   ->with(compact('pageDescription'));

})->before('guest');;

Route::post('/login', function() {
   $credentials = array(
     'email' => Input::get('email'),
     'password' => Input::get('password')
     );

   //var_dump($credentials);

   $password = Hash::make(Input::get('password'));
   // perform validation
   if ( Auth::attempt($credentials) )
   {
      // Credentials match. Logged in!
      //echo 'valid';
      Auth::user()->touch();
      //Symfony\Component\HttpFoundation\Request::trustProxyData();
      Log::info('['.__METHOD__.'] User id ['.Auth::user()->id.'] IP ['.Request::getClientIp().'] logged in');
      //User::find(Auth::user()->id)->touch();

      return Redirect::intended('profile/');
   }
   Log::error('['.Input::get('email') .' failed to login.]');

   return Redirect::to('login')
   ->with('flash_error', 'Combinatia email/parola a fost incorecta.')
   ->withInput(Input::except('password'));
});






/*
|--------------------------------------------------------------------------
| Root /
|--------------------------------------------------------------------------
|
| Here you may configure the connection information for each server that
| is used by your application. A default configuration has been added
| for each back-end shipped with Laravel. You are free to add more.
|
*/
Route::get('/', function() {

   $last10events  = UserEvent::last()->with('orase')->orderBy('created_at')->take(Config::get('sitesettings.lastXevents', 10))->get();
   $last10users   = User::last()->orderBy('created_at')->take(Config::get('sitesettings.lastXusers', 10))->get();
   $last10locatii = Locatie::last()->with('orase')->orderBy('created_at')->take(Config::get('sitesettings.lastXlocatii', 10))->get();;

   $out = merge($last10events, $last10users, function($a1, $a2) {
      return -(strcmp($a1->created_at, $a2->created_at));
   });

   $out = merge($out, $last10locatii, function($a1, $a2) {
      return -(strcmp($a1->created_at, $a2->created_at));
   });

   $ultimeleXnoutati = $out->slice(0, Config::get('sitesettings.ultimeleXnoutati', 10));

   return View::make('index')
      ->with(compact('ultimeleXnoutati'));
});








//add a location
//used in create/edit event
Route::post('locatii/add/', function() {

   $rules = array(
      'name' => 'Required|Min:3|Max:250|noxss_tags',
      'address' => 'Required|Min:5|Max:500|noxss_tags',
      'localitate' => 'Required|Min:1|noxss_tags',
      'sport' => 'Required|Min:1|noxss_tags',
      );

   $v = Validator::make(Input::all(), $rules);
   if ($v->fails()) {
      Log::warning('['.__METHOD__.'] failed to validate arena' . print_r(Input::all(),1));
      $messages = '';
      foreach ($v->messages()->all() as $value) {
         $messages .= $value . ' ';
      }
      return Response::json(array('status' => 'error', 'msg' => 'Adaugarea de arena a esuat.' . $messages));
   }

   $locatie = new Locatie;
   $locatie->name = Input::get('name');
   $locatie->adresa = Input::get('address');
   $locatie->oras_id = Input::get('localitate');
   $locatie->added_by_user_id = Auth::user()->id;

   $locatie->save();

   $locatie->sports()->sync(array('sport_id' => Input::get('sport')));

   $emailArr = $locatie->toArray();
   $emailArr['adresa'] = $locatie->adresa;
   $emailArr['oras'] = $locatie->orase->oras;
   $emailArr['sport'] = $locatie->sports()->first()->name;
   $emailArr['added_by_user_id'] = $locatie->added_by_user_id;
   $emailArr['alias'] = Auth::user()->alias;

   $data = array('emailArr' => $emailArr);

   Mail::send('emails/locatii/newlocatie', $data, function($message) use($emailArr)
   {
      $message->to(Config::get('sitesettings.enotif.areneadmin', 'bogdan.durla@gmail.com'))
      ->subject('vreausajoc - o noua admin locatie a fost adaugata');
   });



   //@todo send email to admin
   return Response::json(array('id' => $locatie->id, 'status' => 'ok', 'msg' => 'Arena a fost adaugata.'));

})->before('auth');




//vsj.ro/locatii/sport-locatii/3
//@called in create/edit event

app/views/contact.blade.php
@extends('master')

@section('breadcrumb')
   <li>Contact</li>
@stop

@section('content')

   <fieldset>
   <legend>Parerea, propunerea ta conteaza!</legend>

   Multumim pentru vizita! <br />
   Foloseste formularul de mai jos pentru a trimite parerile si sugestiile tale.
   <br />
   <br />

   {{ Form::open(array('class' => "form-horizontal", "style" => "line-height: 12px;")) }}


   @if (!is_logged())
   <div class="input-append">
      {{Form::text('email', Input::old('email'), array('class' => 'span3', "placeholder" => "Adresa E-mail"));}}
    <span class="add-on"><i class="icon-envelope"></i></span>
   </div>
   @endif

   <br />
   <br />

   {{Form::textarea('text', Input::old('text'), array(
    'rows'        => '10',
    'cols'        => '120',
    'style'       => "width:500px",
    'placeholder' => "Propunerea ta este..."));}}


   <br />

   @if (!is_logged())
      {{$captcha->html()}}
   @endif

   <br />

   {{Form::submit('Trimite', array('class' => "btn btn-primary"));}}
   {{Form::close();}}

   </fieldset>



@stop

app/views/index.blade.php
@extends('master')


@section('content')

<div>
   <div class="pull-left">
      <h1>Vrei sa faci sport?</h1>
      <h2>E mai usor sa faci sport cu vreausajoc.ro</h2>

      <p>Vrei sa:
            <br />
            - faci sport, sa <b>joci tenis</b>, sa <b>joci fotbal</b>, sau orice alt sport si nu ai cu cine?
            <br />
            - participi sau sa organizeazi evenimente cu sporturile tale preferate?
            <br />
      </p>
      <h3><a href="{{URL::to('/register')}}">Inregistreaza-te</a> in comunitatea vreausajoc.ro.</h3>
      De la pasionati de sport pentru pasionati de sport.


       <h3>Ai o locatie, un teren sintetic sau sala de fitness? <a href="{{URL::to("locatii/create")}}" class="btn btn-warning">Adauga locatia ta</a></h3>
   </div>
   <div class="pull-right">
   <div class="panel panel-default pull-left" style="width: 260px">
     <div class="panel-heading">
         Ultimele noutati pe vreausajoc
      </div>
      <div class="panel-body">
         @foreach($ultimeleXnoutati as $object)
            {{Html::skipfirst('events', '<div class="smallseparator"></div>')}}
            <div>
               @if ($object instanceof UserEvent)
                  evenimentul <a href="{{route('events.show' , $object->id)}}">{{$object->event}}</a>
                  {{--, dmy2js($object->data) --}}
                  {{-- in <span>{{ucfirst(strtolower($object->orase->oras))}}.</span> --}}
               @endif
               @if ($object instanceof User)
                  user-ul {{a_profile($object)}} <!-- s-a inregistrat. -->
               @endif
               @if ($object instanceof Locatie)
                  locatia {{a_locatie($object)}} {{-- din <span>{{ucf($object->orase->oras)}}</span> --}}
               @endif
            </div>

         @endforeach
      </div>
   </div>

<?php
/*
{{--
<div class="panel panel-default pull-left" style="margin-right:10px;width: 280px">
  <div class="panel-heading">
      Ultimii useri inregistrati
   </div>
   <div class="panel-body">
      @foreach($last10users as $user)
      @if(!$user->alias)
         <?php continue;?>
      @endif
         {{Html::skipfirst('users', '<div class="smallseparator"></div>')}}
         <div>
            {{a_profile($user)}}
         </div>
      @endforeach
   </div>
</div>


<div class="panel panel-default pull-left" style="width: 280px">
  <div class="panel-heading">
      Ultimele locatii adaugate
   </div>
   <div class="panel-body">
      @foreach($last10locatii as $locatie)
         {{Html::skipfirst('locatie', '<div class="smallseparator"></div>')}}
         <div>
            {{a_locatie($locatie)}} din <span>{{ucf($locatie->orase->oras)}}</span>
         </div>
      @endforeach
   </div>
</div>
--}}
*/
?>

   </div>
</div>

@stop

{{--
<h4><a href="{{URL::to("locatii/create")}}" class="btn btn-primary">Adauga locatia ta</a></h4>
<h4><a href="{{URL::to("locatii/create")}}" class="btn btn-info">Adauga locatia ta</a></h4>
<h4><a href="{{URL::to("locatii/create")}}" class="btn btn-success">Adauga locatia ta</a></h4>
<h4><a href="{{URL::to("locatii/create")}}" class="btn btn-danger">Adauga locatia ta</a></h4>
<h4><a href="{{URL::to("locatii/create")}}" class="btn btn-inverse">Adauga locatia ta</a></h4>
<h4><a href="{{URL::to("locatii/create")}}" class="btn btn-warning">Adauga locatia ta</a></h4>


btn btn-primary   Provides extra visual weight and identifies the primary action in a set of buttons
Info  btn btn-info   Used as an alternative to the default styles
Success  btn btn-success   Indicates a successful or positive action
Warning  btn btn-warning   Indicates caution should be taken with this action
Danger   btn btn-danger Indicates a dangerous or potentially negative action
Inverse  btn btn-inverse   Alternate dark gray button, not tied to a semantic action or use
Link  btn btn-link
--}}

app/views/master.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
@section('metadesc')
<?php
if(isset($pageDescription)) {
   echo $pageDescription;
}
else {
   echo 'Site pentru cei vor sa faca sport. Organizare evenimente sportive.';
}


?>
@stop
@section('head')
    <meta charset="UTF-8">
    <title>@if(isset($pageTitle)){{$pageTitle}} - @endif vreausajoc.ro</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="@yield('metadesc')">
    <meta name="keywords" content="vreausajoc.ro, vreau sa fac sport, vreau sa joc, evenimente sportive"/>
    <meta name="author" content="vreausajoc.ro">

   {{-- using reddint style of font
   @if (app()->environment() != 'local')
   <style>
     @import url(https://fonts.googleapis.com/css?family=Ubuntu);
   </style>
   @endif
   --}}

    {{ Html::style('css/bootstrap-utd.css') }}
    {{ Html::style('css/css.css') }}
    {{ Html::style('css/panel.css') }}

    {{ Html::style('css/bootstrap-responsive.min.css') }}
    {{ Html::style('css/css-resp.css') }}

    {{ Html::script('js/jquery-1.9.0.min.js') }}
    {{ Html::script('js/bootstrap.js') }}

    {{ Html::script('js/vsj.js') }}

    <link rel="shortcut icon" href="/img/ico/favicon.ico">
    {{--
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/img/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/img/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/img/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/img/ico/apple-touch-icon-57-precomposed.png">
    --}}


   @if (app()->environment() != 'local')
      {{-- javascript script tag included --}}
      @include('_parts.clicktale_start')
   @endif

   <script type="text/javascript">

   $(function() {
      $.defaultsLoggedId = '<?php echo (Auth::user()) ? Auth::user()->id : ""?>';
   });



   function loader() {
      var id = 'loader_' + (+new Date());
      return ['<div id="' + id + '"><img style="padding:2px;vertical-align:middle" src="/img/ajax-loader.gif>se incarca</div>', id];
   }
   function ci() {
      console.info(arguments);
   }

   </script>
@show
</head>

<body class="preview" data-spy="scroll" data-target=".subnav" data-offset="80">

@section('topmenu')
<div class="navbar navbar-fixed-top">
<div class="navbar-inner">
 <div class="container">
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <a class="brand" href="{{URL::to('/')}}">vreausajoc</a>
    <div class="nav-collapse collapse">
      <ul class="nav pull-right">
         @if(Auth::check())
            <li><a href="{{URL::to('profile')}}"><i class="icon-user"></i> {{Auth::user()->alias}}</a></li>
            <li><a href="{{URL::to('logout')}}"><i class="icon-off"></i> Logout</a></li>
         @else
            <li><a href="{{URL::to('register')}}">Inregistrare</a></li>
            <li><a href="{{URL::to('login')}}">Login</a></li>
         @endif
      </ul>
    </div><!--/.nav-collapse -->
  </div>
 </div>
</div><!-- navbar navbar-fixed-top -->
@stop

@section('leftmenu')
   <div class="span3">
      <div class="well sidebar-nav">
         <ul class="nav nav-list">

            @if (Auth::check())
               <li class="nav-header">Contul meu</li>

               <li @if (Request::segment(1) == 'profile' && Request::segment(2) == '') class="active" @endif>
                  <a href="{{URL::to('profile')}}">Profil</a>

                  @if (Request::segment(1) == 'profile' && (Request::segment(2) == '' || Request::segment(3) == 'edit'))
                  <ul class="level0">
                     <li @if (Request::segment(3) == 'edit') class="active level1" @else class="level1" @endif>
                     <a href="{{route('profile.edit', $user->id)}}">Editeaza profil</a></li>
                     </li>
                  </ul>
                  @endif
               </li>


               <li @if (Request::segment(1) == 'events' && Request::segment(2) == '') class="active" @endif>
                  <a href="{{URL::to('events')}}">Evenimente</a>

                  @if (Request::segment(1) == 'events' && (Request::segment(2) == '' || Request::segment(3) == 'create'))
                  <ul class="level0">
                     <li @if (Request::segment(3) == 'create')  class="active level1 " @else 'class="level1"' @endif>
                        <a href="{{URL::to('events/create')}}">Creeaza eveniment</a>
                     </li>
                  </ul>
                  @endif
              </li>

               <li @if (Request::segment(1) == 'convocari' && Request::segment(2) == '') 'class="active"' @endif>
                  <a href="{{URL::to('convocari')}}">Convocari</a>
               </li>

            @endif


            <li class="nav-header">Admin</li>
            <li>
               <ul class="level0">
               </ul>
            </li>
            <li><a href="#">Link</a></li>
         </ul> <!-- menu -->
      </div><!--/.well -->
   </div><!--/span-->
@stop

@yield('topmenu')

@section('container')
   <div class="container">
      <div class="row">

      @if (Request::segment(1) != 'login' && Request::segment(1) != 'register' && Request::segment(1) != 'logout' && Request::segment(1) != 'forgot')
         @include('_parts.menu')

         <div class="span9">
            <ul class="breadcrumb">
               @section('breadcrumbs')
                  <li>
                     <a href="{{URL::to("/")}}">{{Config::get('sitesettings.breadsitename')}}</a>
                     <span class="divider">/</span>
                  </li>
                  @yield('breadcrumb')
               @show
            </ul>

         @include('_parts.errors')

         @yield('content')

         </div> <!-- div class="span9" -->

      @else
         @yield('content')
      @endif


      </div><!-- /row in center container-->
@show

@section('footer')
<footer>
<hr>
<div>
   <div class="pull-left">&copy; {{Config::get('sitesettings.sitename', 'vreausajoc.ro');}} {{date('Y')}}</div>
   <div class="pull-right">
      <a href="{{URL::to('contact')}}">Contact</a>
   </div>
</div>

@if (app()->environment() != 'local')
   @include('_parts.analytics')
@endif
</footer>
</div><!--/.container </div> in footer end-->

   @if (app()->environment() != 'local')
      {{-- javascript script tag included --}}
      @include('_parts.clicktale_end')
   @endif

</body>
</html>
@show